// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_MIXEDSORT_cpp
IntegerVector get_MIXEDSORT_cpp(CharacterVector x, bool dec);
RcppExport SEXP _DiscreteMorseR_get_MIXEDSORT_cpp(SEXP xSEXP, SEXP decSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type dec(decSEXP);
    rcpp_result_gen = Rcpp::wrap(get_MIXEDSORT_cpp(x, dec));
    return rcpp_result_gen;
END_RCPP
}
// get_vOUT
List get_vOUT(DataFrame v, CharacterVector ve_e_p);
RcppExport SEXP _DiscreteMorseR_get_vOUT(SEXP vSEXP, SEXP ve_e_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type v(vSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ve_e_p(ve_e_pSEXP);
    rcpp_result_gen = Rcpp::wrap(get_vOUT(v, ve_e_p));
    return rcpp_result_gen;
END_RCPP
}
// get_vertTO_cpp
DataFrame get_vertTO_cpp(DataFrame vertex, DataFrame edge, DataFrame face);
RcppExport SEXP _DiscreteMorseR_get_vertTO_cpp(SEXP vertexSEXP, SEXP edgeSEXP, SEXP faceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type vertex(vertexSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type face(faceSEXP);
    rcpp_result_gen = Rcpp::wrap(get_vertTO_cpp(vertex, edge, face));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DiscreteMorseR_get_MIXEDSORT_cpp", (DL_FUNC) &_DiscreteMorseR_get_MIXEDSORT_cpp, 2},
    {"_DiscreteMorseR_get_vOUT", (DL_FUNC) &_DiscreteMorseR_get_vOUT, 2},
    {"_DiscreteMorseR_get_vertTO_cpp", (DL_FUNC) &_DiscreteMorseR_get_vertTO_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_DiscreteMorseR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
