# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_MESH_cpp <- function(vertices, faces) {
    .Call(`_DiscreteMorseR_get_MESH_cpp`, vertices, faces)
}

get_MIXEDSORT_cpp <- function(x, dec = TRUE) {
    .Call(`_DiscreteMorseR_get_MIXEDSORT_cpp`, x, dec)
}

get_vOUT <- function(v, ve_e_p) {
    .Call(`_DiscreteMorseR_get_vOUT`, v, ve_e_p)
}

get_vertTO_cpp <- function(vertex, edge, face) {
    .Call(`_DiscreteMorseR_get_vertTO_cpp`, vertex, edge, face)
}

